### ISSUE TITLE
NPE in PlaceHoldActivity$1.run

### ISSUE THREAD

**Issue by kenstir** [kenstir/hemlock#11]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at org.evergreen_ils.accountAccess.holds.PlaceHoldActivity$1.run(PlaceHoldActivity.java:187)
       at java.lang.Thread.run(Thread.java:764)

**Comment by kenstir** [comment]
`187                if (eg.getSMSCarriers().size() > selectedSMSPos)`

**Comment by kenstir** [comment]
https://fabric.io/appskenstirnet/android/apps/net.kenstir.apps.pines/issues/5a34758e8cb3c2fa63f9f754?

**Comment by kenstir** [comment]
So many NPEs were fixed with the refactor into Kotlin and coroutines.
