### ISSUE TITLE
NPE in CircRecord()

### ISSUE THREAD

**Issue by kenstir** [kenstir/hemlock#12]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.opensrf.util.OSRFObject.getString(java.lang.String)' on a null object reference
       at org.evergreen_ils.accountAccess.checkout.CircRecord.<init>(CircRecord.java:80)
       at org.evergreen_ils.accountAccess.AccountAccess.getItemsCheckedOut(AccountAccess.java:297)
       at org.evergreen_ils.accountAccess.checkout.ItemsCheckOutListView$2.run(ItemsCheckOutListView.java:119)
       at java.lang.Thread.run(Thread.java:818)
```
Crashlytics #6
https://fabric.io/appskenstirnet/android/apps/net.kenstir.apps.pines/issues/5a3556fa8cb3c2fa63069f0d?

**Comment by kenstir** [comment]
Not sure why, but it looks like the circ object was null.  Workaround in place for now.

**Comment by kenstir** [comment]
So many NPEs were fixed with the refactor into Kotlin and coroutines.
