### ISSUE TITLE
NPE in EvergreenServerLoader

### ISSUE THREAD

**Issue by kenstir** [kenstir/hemlock#13]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kenstir.apps.pines/org.evergreen_ils.views.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.Integer org.evergreen_ils.system.Organization.id' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.Integer org.evergreen_ils.system.Organization.id' on a null object reference
       at org.evergreen_ils.system.EvergreenServerLoader$1.compare(EvergreenServerLoader.java:102)
       at org.evergreen_ils.system.EvergreenServerLoader$1.compare(EvergreenServerLoader.java:99)
       at java.util.TimSort.binarySort(TimSort.java:296)
       at java.util.TimSort.sort(TimSort.java:239)
       at java.util.Arrays.sort(Arrays.java:1523)
       at java.util.Collections.sort(Collections.java:238)
       at org.evergreen_ils.system.EvergreenServerLoader.fetchOrgSettings(EvergreenServerLoader.java:99)
       at org.evergreen_ils.views.MainActivity.onCreate(MainActivity.java:67)
       at android.app.Activity.performCreate(Activity.java:6912)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

https://fabric.io/appskenstirnet/android/apps/net.kenstir.apps.pines/issues/5a3d4f868cb3c2fa63746d01?time=last-seven-days

**Comment by kenstir** [comment]
timing issue: home org not loaded yet

**Comment by kenstir** [comment]
So many NPEs were fixed with the refactor into Kotlin and coroutines.
