### ISSUE TITLE
NPE in handleMenuAction

### ISSUE THREAD

**Issue by kenstir** [kenstir/hemlock#14]
Crashlytics issue # 15

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at java.net.URLEncoder.encode(URLEncoder.java:205)
       at java.net.URLEncoder.encode(URLEncoder.java:171)
       at org.evergreen_ils.utils.ui.BaseActivity.handleMenuAction(BaseActivity.java:189)
       at org.evergreen_ils.views.MainActivity.onOptionsItemSelected(MainActivity.java:186)
       at org.evergreen_ils.views.MainActivity$2.onClick(MainActivity.java:153)
       at android.view.View.performClick(View.java:6207)
       at android.view.View$PerformClick.run(View.java:23639)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by kenstir** [comment]
So many NPEs were fixed with the refactor into Kotlin and coroutines.
