### ISSUE TITLE
ClassCastException: java.util.ArrayList cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by kenstir** [kenstir/hemlock#15]
Fatal Exception: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
       at org.evergreen_ils.accountAccess.AccountAccess.renewCirc(AccountAccess.java:586)
       at org.evergreen_ils.accountAccess.checkout.ItemsCheckOutListView$3.run(ItemsCheckOutListView.java:254)
       at java.lang.Thread.run(Thread.java:818)

Hemlock crashes # 12, 13, 14

**Comment by kenstir** [comment]
renewCirc was crashing on a response which was an event (MAX_RENEWALS_REACHED) or list of events (PATRON_EXCEEDS_FINES + PATRON_EXCEEDS_LOST_COUNT).
